
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Woody
 */
public class Menu extends javax.swing.JFrame {
    boolean check = false;
    /**
     * Creates new form f4b
     */
    public Menu() {
        initComponents();
        //this code centers the box and prevents it from being resized
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InspireBox = new javax.swing.JButton();
        RateActivityButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        NoPeopleBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        TypeBox = new javax.swing.JComboBox<>();
        IndoorOrOutdoorBox = new javax.swing.JComboBox<>();
        LengthOfTimeBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RatingValue = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome ___________ ");

        jLabel2.setText("Would you like to find an activity to do or edit your activities?");

        InspireBox.setText("Inspire me");
        InspireBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InspireBoxActionPerformed(evt);
            }
        });

        RateActivityButton.setText("Rate activity");
        RateActivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RateActivityButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");

        jButton4.setText("Return");

        jButton5.setText("Manage Activities");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        NoPeopleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        NoPeopleBox.setSelectedIndex(2);

        jLabel3.setText("Type");

        TypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sport", "Hobby", "Boardgame" }));
        TypeBox.setSelectedIndex(2);

        IndoorOrOutdoorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Don't mind", "Indoor", "Outdoor" }));
        IndoorOrOutdoorBox.setSelectedIndex(1);
        IndoorOrOutdoorBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndoorOrOutdoorBoxActionPerformed(evt);
            }
        });

        LengthOfTimeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Don't mind", "5 min", "10 min", "15 min", "30 min", "1hr", "2hrs", "4hrs" }));
        LengthOfTimeBox.setSelectedIndex(6);
        LengthOfTimeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LengthOfTimeBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Last activity:");

        jLabel5.setText("Tennis on 15/04/2021");

        RatingValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel6.setText("No.People");

        jLabel7.setText("Indoors/Outdoors");

        jLabel8.setText("Length of time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InspireBox, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(RatingValue, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RateActivityButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NoPeopleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(IndoorOrOutdoorBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(LengthOfTimeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoPeopleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IndoorOrOutdoorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LengthOfTimeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InspireBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RatingValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RateActivityButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RateActivityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RateActivityButtonActionPerformed
        //this is a test run where it will only update the first row of the activity history
        int rating = Integer.parseInt((String)RatingValue.getSelectedItem());
        Statement stmt = null;
        Connection conn = null;
        try{
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (Exception e){
            System.out.println(e);
        }
        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","reigatecollege");
        stmt = (Statement) conn.createStatement();
        //this part is just to test, what is changed can only be set here
        String q ="update activityhistory set Rating='" + rating + "' " + "where ActivityID in (1) and UserID in (1)";
        stmt.executeUpdate(q);
        } catch (SQLException excep){
            excep.printStackTrace();
        } catch(Exception excep){
            JOptionPane.showMessageDialog(null, "Error");
        } finally {
            if(stmt != null){
                try {
                    conn.close();
                } catch (SQLException se) {}
                try {
                    if(conn != null)
                        conn.close();
                } catch (SQLException se){
                    se.printStackTrace();
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Rated");
        //"check" makes sure that the test activity has been rated
        check = true;
    }//GEN-LAST:event_RateActivityButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void IndoorOrOutdoorBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndoorOrOutdoorBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IndoorOrOutdoorBoxActionPerformed

    private void LengthOfTimeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LengthOfTimeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LengthOfTimeBoxActionPerformed

    private void InspireBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InspireBoxActionPerformed
        //this code searches for a valid activity to do
          if(check == true){
          String type = (String) TypeBox.getSelectedItem();
          int people = Integer.valueOf((String) NoPeopleBox.getSelectedItem());
          String indoor = (String) IndoorOrOutdoorBox.getSelectedItem();
          int time = LengthOfTimeBox.getSelectedIndex();
          
          int activitytype;
          
          //this part converts the type from string to int which is what it is like in mySQL, i can have it done above enstead though
          if(type.equals("Sport")){
              activitytype = 1;
          } else if (type.equals("Hobby")){
              activitytype = 2;
          } else {
              activitytype = 3;
          }
          
          int activitytime = 0;
          //this part of the program converts the time to a valid variable
          if(time == 1){
              activitytime = 5;
          } else if (time == 2){
              
              activitytime = 10;
              
          } else if (time == 3){
              
              activitytime = 15;
              
          } else if (time == 4){
              
              activitytime = 30;
              
          } else if (time == 5){
              
              activitytime = 60;
              
          } else if (time == 6){
              
              activitytime = 120;
              
          } else if (time == 7){
              
              activitytime = 240;
              
          }
          try{
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","reigatecollege");
         String q="SELECT * FROM activity WHERE ActivityType='" + activitytype + "' AND MinPeople<='" + people + "' AND MaxPeople>='" + people + "' AND IndoorOrOutdoor='" + indoor + "' AND LengthOfTime='" + activitytime + "';";
         //Statement st=con.prepareStatement("SELECT * FROM activity WHERE ActivityType='" + activitytype + "' AND MinPeople='" + people + "' AND IndoorOrOutdoor='" + indoor + "' AND LengthOfTime='" + activitytime + "';",
         Statement st=con.prepareStatement(q,
         //RAND() Function
         ResultSet.TYPE_SCROLL_SENSITIVE,
         ResultSet.CONCUR_UPDATABLE);
         ResultSet rs=st.executeQuery(q);
         Random rand = new Random();
         int size = 0;
         //JOptionPane.showMessageDialog(null, "Gate 1 - "+q);
         if (rs != null){
             rs.last();
             size = rs.getRow();
             rs.first();
             //JOptionPane.showMessageDialog(null, "Gate 2 - "+size);
         }
         if(size > 0){
         int pos = rand.nextInt(size);
         for(int i = 0; i < pos; i++){
             rs.next();
         }
         }
         if(activitytype != 3){
             JOptionPane.showMessageDialog(null, "How about you do " + rs.getString("ActivityName") + "?");
         } else {
             JOptionPane.showMessageDialog(null, "How about you play " + rs.getString("ActivityName") + "?");
         }
         JOptionPane.showMessageDialog(null, rs.getString("Details"));
         } catch(Exception e){
        JOptionPane.showMessageDialog(null, "Sorry but there weren't any activities with that detail at the moment");
        }
          } else {
              JOptionPane.showMessageDialog(null, "You must rate your activities first");
          }    
    }//GEN-LAST:event_InspireBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> IndoorOrOutdoorBox;
    private javax.swing.JButton InspireBox;
    private javax.swing.JComboBox<String> LengthOfTimeBox;
    private javax.swing.JComboBox<String> NoPeopleBox;
    private javax.swing.JButton RateActivityButton;
    private javax.swing.JComboBox<String> RatingValue;
    private javax.swing.JComboBox<String> TypeBox;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
